[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai","@deepgram/sdk","mongodb","@supabase/supabase-js","@supabase/ssr","sharp","tesseract.js"]
  included_files = ["public/test-assets/**"]
  timeout = 26
  memory = 1024

# Function-specific overrides (if supported by Netlify plan)
[functions."next_api_*"]
  timeout = 26
  memory = 1024