[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp", "tesseract.js", "@deepgram/sdk", "@google/generative-ai", "mongodb", "@supabase/supabase-js", "@supabase/ssr"]
  node_bundler = "esbuild"